// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for neon_auth.users_sync */
export type UsersSyncId = string & { __brand: 'neon_auth.users_sync' };

/** Represents the table neon_auth.users_sync */
export default interface UsersSync {
  id: UsersSyncId;

  raw_json: unknown;

  name: string | null;

  email: string | null;

  created_at: Date | null;

  updated_at: Date | null;

  deleted_at: Date | null;
}

/** Represents the initializer for the table neon_auth.users_sync */
export interface UsersSyncInitializer {
  raw_json: unknown;

  updated_at?: Date | null;

  deleted_at?: Date | null;
}

/** Represents the mutator for the table neon_auth.users_sync */
export interface UsersSyncMutator {
  raw_json?: unknown;

  updated_at?: Date | null;

  deleted_at?: Date | null;
}
