// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as AvatarComponentType } from './AvatarComponentType';

/** Identifier type for public.avatar_components */
export type AvatarComponentsId = number & { __brand: 'public.avatar_components' };

/** Represents the table public.avatar_components */
export default interface AvatarComponents {
  id: AvatarComponentsId;

  filename: string;

  type: AvatarComponentType;
}

/** Represents the initializer for the table public.avatar_components */
export interface AvatarComponentsInitializer {
  filename: string;

  type: AvatarComponentType;
}

/** Represents the mutator for the table public.avatar_components */
export interface AvatarComponentsMutator {
  filename?: string;

  type?: AvatarComponentType;
}
