// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.avatar_component_type */
enum AvatarComponentType {
  eyes = 'eyes',
  mouth = 'mouth',
};

export default AvatarComponentType;
