// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.user */
export type UserId = string & { __brand: 'public.user' };

/** Represents the table public.user */
export default interface User {
  id: UserId;

  name: string;

  email: string;

  password: string;

  date_joined: Date;

  phone_number: string | null;

  date_of_birth: Date | null;

  bio: string;
}

/** Represents the initializer for the table public.user */
export interface UserInitializer {
  /** Default value: gen_random_uuid() */
  id?: UserId;

  name: string;

  email: string;

  password: string;

  /** Default value: now() */
  date_joined?: Date;

  phone_number?: string | null;

  date_of_birth?: Date | null;

  /** Default value: ''::character varying */
  bio?: string;
}

/** Represents the mutator for the table public.user */
export interface UserMutator {
  id?: UserId;

  name?: string;

  email?: string;

  password?: string;

  date_joined?: Date;

  phone_number?: string | null;

  date_of_birth?: Date | null;

  bio?: string;
}
