// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AvatarComponentsId } from './AvatarComponents';

/** Identifier type for public.users */
export type UsersId = string & { __brand: 'public.users' };

/** Represents the table public.users */
export default interface Users {
  id: UsersId;

  name: string;

  email: string;

  password: string;

  date_joined: Date;

  phone_number: string | null;

  date_of_birth: Date | null;

  bio: string;

  is_admin: boolean;

  avatar_eyes: AvatarComponentsId;

  avatar_mouth: AvatarComponentsId;

  avatar_colour: string;
}

/** Represents the initializer for the table public.users */
export interface UsersInitializer {
  /** Default value: gen_random_uuid() */
  id?: UsersId;

  name: string;

  email: string;

  password: string;

  /** Default value: now() */
  date_joined?: Date;

  phone_number?: string | null;

  date_of_birth?: Date | null;

  /** Default value: ''::character varying */
  bio?: string;

  /** Default value: false */
  is_admin?: boolean;

  /** Default value: 4 */
  avatar_eyes?: AvatarComponentsId;

  /** Default value: 30 */
  avatar_mouth?: AvatarComponentsId;

  /** Default value: 'FFFF00'::character varying */
  avatar_colour?: string;
}

/** Represents the mutator for the table public.users */
export interface UsersMutator {
  id?: UsersId;

  name?: string;

  email?: string;

  password?: string;

  date_joined?: Date;

  phone_number?: string | null;

  date_of_birth?: Date | null;

  bio?: string;

  is_admin?: boolean;

  avatar_eyes?: AvatarComponentsId;

  avatar_mouth?: AvatarComponentsId;

  avatar_colour?: string;
}
