// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.users */
export type UsersId = string & { __brand: 'public.users' };

/** Represents the table public.users */
export default interface Users {
  id: UsersId;

  name: string;

  email: string;

  password: string;

  date_joined: Date;

  phone_number: string | null;

  date_of_birth: Date | null;

  bio: string;
}

/** Represents the initializer for the table public.users */
export interface UsersInitializer {
  /** Default value: gen_random_uuid() */
  id?: UsersId;

  name: string;

  email: string;

  password: string;

  /** Default value: now() */
  date_joined?: Date;

  phone_number?: string | null;

  date_of_birth?: Date | null;

  /** Default value: ''::character varying */
  bio?: string;
}

/** Represents the mutator for the table public.users */
export interface UsersMutator {
  id?: UsersId;

  name?: string;

  email?: string;

  password?: string;

  date_joined?: Date;

  phone_number?: string | null;

  date_of_birth?: Date | null;

  bio?: string;
}
